import Head from "next/head";

import Header from "./header";
import Footer from "./footer";
import Main from "./main";
import Background from "./background";

export default function Home() {
  return (
    <div className="area">
      <Head>
        <title>colorjo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <Main></Main>

      <Footer></Footer>
      
      <Background></Background>
    </div>
  );
}
