import Head from "next/head";

import Header from "./header";
import Footer from "./footer";
import Main from "./main";
import Background from "./background";
import Generated from "./generated";

export default function Home() {
  return (
    <div className="area">
      <Head>
        <title>colorjo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex flex-col">
        <Header></Header>
  
        <Main></Main>
      </div>

      <Generated></Generated>

      <Footer></Footer>
      
      <Background></Background>
    </div>
  );
}
